"""Mini-Graphify — auto-generate a docs/wiki/architecture.md from the source tree.

Walks ``src/marl_lab`` and emits a Markdown file that lists every module with
its top-line docstring and the public symbols it exports. This is the same
pattern used in A4/A5; it documents the code so a TA can audit structure
without reading every file."""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


@dataclass
class ModuleSummary:
    """Per-module summary used by Graphify."""
    path: Path
    docstring: str
    public_symbols: list[str]
    loc: int


def summarise_module(path: Path) -> ModuleSummary:
    """Read a Python file and extract its docstring + public top-level symbols."""
    text = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError:
        return ModuleSummary(path=path, docstring="(syntax error)", public_symbols=[], loc=0)
    docstring = ast.get_docstring(tree) or ""
    symbols: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            if not node.name.startswith("_"):
                symbols.append(node.name)
        elif isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name) and not tgt.id.startswith("_"):
                    symbols.append(tgt.id)
    loc = len(text.splitlines())
    return ModuleSummary(path=path, docstring=docstring, public_symbols=symbols, loc=loc)


def walk_source_tree(src_dir: Path) -> list[ModuleSummary]:
    """Walk all .py files under ``src_dir`` (skip ``__pycache__``) — sorted."""
    out: list[ModuleSummary] = []
    for p in sorted(src_dir.rglob("*.py")):
        if "__pycache__" in p.parts:
            continue
        if p.name == "__init__.py" and p.stat().st_size == 0:
            continue
        out.append(summarise_module(p))
    return out


def format_markdown(summaries: list[ModuleSummary], src_dir: Path) -> str:
    """Render summaries as a single Markdown document."""
    lines = ["# marl_lab — auto-generated architecture overview\n",
             "Generated by `marl_lab.graphify`. Do not edit by hand.\n"]
    pillar_groups: dict[str, list[ModuleSummary]] = {}
    for s in summaries:
        relpath = s.path.relative_to(src_dir.parent.parent)
        pillar = relpath.parts[2] if len(relpath.parts) >= 4 else "shared"
        pillar_groups.setdefault(pillar, []).append(s)
    for pillar, group in sorted(pillar_groups.items()):
        lines.append(f"\n## {pillar}/\n")
        for s in group:
            rel = s.path.relative_to(src_dir.parent.parent)
            doc = (s.docstring.split("\n")[0] if s.docstring else "(no docstring)")
            symbols = ", ".join(s.public_symbols[:8])
            lines.append(f"- **{rel}** ({s.loc} LOC) — {doc}")
            if symbols:
                lines.append(f"  - exports: `{symbols}`")
    return "\n".join(lines) + "\n"


def run(src_dir: str | Path, output_path: str | Path) -> Path:
    """Generate the architecture.md file. Returns the output path."""
    src_dir = Path(src_dir)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summaries = walk_source_tree(src_dir)
    output_path.write_text(format_markdown(summaries, src_dir))
    return output_path
