"""Build a provenance dict that proves which code produced a given report.

Used to extend GameReport JSON with reproducibility metadata: git SHA of
the running tree, library versions, Python version, host info. A TA can
then verify that the report was generated by the exact commit they're
grading."""

from __future__ import annotations

import platform
import subprocess
import sys


def _git_sha(cwd: str | None = None) -> str:
    """Return the short git SHA of the current HEAD, or 'unknown'."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=cwd, timeout=2, check=True,
        )
        return out.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError):
        return "unknown"


def _git_dirty(cwd: str | None = None) -> bool:
    """True if the working tree has uncommitted changes to TRACKED files.

    v1.19: was ``git status --porcelain`` (counted untracked files too),
    which reported ``git_dirty: true`` in a clean submission just because
    an unrelated scratch dir or a ``.DS_Store`` existed elsewhere in the
    repo. For reproducibility semantics we only care about modifications
    to files git knows about — a fresh ``git checkout <sha>`` restores
    those exactly; it can't restore files git never tracked."""
    try:
        # Exit 0 = no diff to tracked files; exit 1 = there are diffs
        rc = subprocess.run(
            ["git", "diff", "--quiet", "HEAD"],
            capture_output=True, cwd=cwd, timeout=2,
        ).returncode
        return rc != 0
    except (subprocess.SubprocessError, FileNotFoundError):
        return True


def collect_provenance() -> dict:
    """Build the full provenance dict for embedding into a GameReport."""
    from marl_lab.shared.version import __version__
    info: dict[str, str | bool] = {
        "marl_lab_version": __version__,
        "git_sha": _git_sha(),
        "git_dirty": _git_dirty(),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
    }
    # Versions of the libraries that materially affect numerics
    for lib in ("numpy", "torch", "matplotlib"):
        try:
            mod = __import__(lib)
            info[f"{lib}_version"] = getattr(mod, "__version__", "unknown")
        except ImportError:
            info[f"{lib}_version"] = "missing"
    return info
