"""Build a provenance dict that proves which code produced a given report.

Used to extend GameReport JSON with reproducibility metadata: git SHA of
the running tree, library versions, Python version, host info. A TA can
then verify that the report was generated by the exact commit they're
grading."""

from __future__ import annotations

import platform
import subprocess
import sys


def _git_sha(cwd: str | None = None) -> str:
    """Return the short git SHA of the current HEAD, or 'unknown'."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=cwd, timeout=2, check=True,
        )
        return out.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError):
        return "unknown"


def _git_dirty(cwd: str | None = None) -> bool:
    """True if the working tree has uncommitted changes."""
    try:
        out = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, cwd=cwd, timeout=2, check=True,
        )
        return bool(out.stdout.strip())
    except (subprocess.SubprocessError, FileNotFoundError):
        return True


def collect_provenance() -> dict:
    """Build the full provenance dict for embedding into a GameReport."""
    from marl_lab.shared.version import __version__
    info: dict[str, str | bool] = {
        "marl_lab_version": __version__,
        "git_sha": _git_sha(),
        "git_dirty": _git_dirty(),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
    }
    # Versions of the libraries that materially affect numerics
    for lib in ("numpy", "torch", "matplotlib"):
        try:
            mod = __import__(lib)
            info[f"{lib}_version"] = getattr(mod, "__version__", "unknown")
        except ImportError:
            info[f"{lib}_version"] = "missing"
    return info
